spring.application.name=sacredsikkimapi

spring.datasource.url=jdbc:mysql://bzyroexzctudzspo7yd5-mysql.services.clever-cloud.com:3306/bzyroexzctudzspo7yd5
spring.datasource.username=uopq4fsaju0d0wn2
spring.datasource.password=SgtmoLEgYN8qgosf8k8z
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-256-bit-base64-secret